*This is an autoreload extension for Jupyter that allows Jupyter towards the source code of the module.*

In [1]:
%load_ext autoreload
%autoreload 2

# 1. Data Sourcing And Exploration

In this section we will be going through the straightforward steps to read our raw data and exploring it. For this project we will be using the "(Loxia_Megapaglaga)ebd_hiscro_relApr-2026.txt" and the checklists in the region "ebd_DO_relApr-2026.txt" files provided by the Cornell Lab of Ornithology in the month of April 2026. If you're interested in the source of data you'll need to request [eBird Data Access](https://ebird.org/data/download?continue).

****

**Reading our data**

In [2]:
import pandas as pd

#The ".." means go up one directory, so this path is going to the data folder, then the raw folder, and then the file name."

path1 = '../data/raw/(Loxia_Megapaglaga)ebd_hiscro_relApr-2026.txt'

path2 = '../data/raw/ebd_DO_relApr-2026.txt'

df1 = pd.read_csv(path1, sep='\t', low_memory = False)

df2 = pd.read_csv(path2, sep='\t', low_memory = False)

In [3]:
df1.head(5)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS209001187,2025-10-02 12:09:28.434474,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,3.0,1,NaN,0,1,0,NaN,Relevamiento rapido de 3 dias,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS3509436961,2025-10-02 13:55:11.317351,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,NaN,1,NaN,0,1,0,NaN,WINGS Birding Tours - Leaders: Gavin Bieber an...,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1870620934,2025-10-02 11:36:52.354416,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,4.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS2425022580,2024-08-31 10:45:49.795758,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,5.0,1,NaN,1,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1654293781,2025-10-04 12:50:19.761621,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN

In [4]:
df2.head(5)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS3144018641,2025-05-08 13:55:10.983436,4188,species,avibase-C2077AD8,Antillean Palm Swift,Tachornis phoenicobia,NaN,NaN,NaN,...,1.0,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male collected on this date near Puerto Pl...,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS3144018648,2025-05-08 13:55:11.008615,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,NaN,NaN,NaN,...,2.0,0,NaN,0,1,0,NaN,In US National Museum or Field Museum of Natur...,one female collected on this date near Puerto ...,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS3144018640,2025-05-08 13:55:10.978498,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,NaN,NaN,NaN,...,1.0,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male and one female collected on this date...,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS3144018645,2025-05-08 13:55:10.993761,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,NaN,NaN,NaN,...,1.0,0,NaN,0,1,0,NaN,In Harvard Museum of Comparative Zoology or Fi...,one male collected on this date near Puerto Pl...,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS3144018635,2025-05-08 13:55:10.907722,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,NaN,NaN,NaN,...,2.0,0,NaN,0,1,0,NaN,In Field Museum of Natural History and US Nati...,three females collected on this date near Puer...,NaN

**Exploring our data**

In [8]:
type(df2)

pandas.DataFrame

In [6]:
df1.columns

Index(['GLOBAL UNIQUE IDENTIFIER', 'LAST EDITED DATE', 'TAXONOMIC ORDER',
       'CATEGORY', 'TAXON CONCEPT ID', 'COMMON NAME', 'SCIENTIFIC NAME',
       'SUBSPECIES COMMON NAME', 'SUBSPECIES SCIENTIFIC NAME', 'EXOTIC CODE',
       'OBSERVATION COUNT', 'BREEDING CODE', 'BREEDING CATEGORY',
       'BEHAVIOR CODE', 'AGE/SEX', 'COUNTRY', 'COUNTRY CODE', 'STATE',
       'STATE CODE', 'COUNTY', 'COUNTY CODE', 'IBA CODE', 'BCR CODE',
       'USFWS CODE', 'ATLAS BLOCK', 'LOCALITY', 'LOCALITY ID', 'LOCALITY TYPE',
       'LATITUDE', 'LONGITUDE', 'OBSERVATION DATE',
       'TIME OBSERVATIONS STARTED', 'OBSERVER ID', 'OBSERVER ORCID ID',
       'SAMPLING EVENT IDENTIFIER', 'OBSERVATION TYPE', 'PROTOCOL NAME',
       'PROTOCOL CODE', 'PROJECT NAMES', 'PROJECT IDENTIFIERS',
       'DURATION MINUTES', 'EFFORT DISTANCE KM', 'EFFORT AREA HA',
       'NUMBER OBSERVERS', 'ALL SPECIES REPORTED', 'GROUP IDENTIFIER',
       'HAS MEDIA', 'APPROVED', 'REVIEWED', 'REASON', 'CHECKLIST COMMENTS',
       'SPECIES COMMENTS', 'Unnamed: 52'],
      dtype='str')

In [ ]:
for i, col in enumerate(df1.columns):
    print(i, col)

GLOBAL UNIQUE IDENTIFIER 0
LAST EDITED DATE 0
TAXONOMIC ORDER 0
CATEGORY 0
TAXON CONCEPT ID 0
COMMON NAME 0
SCIENTIFIC NAME 0
SUBSPECIES COMMON NAME 860373
SUBSPECIES SCIENTIFIC NAME 860373
EXOTIC CODE 839944
OBSERVATION COUNT 0
BREEDING CODE 883387
BREEDING CATEGORY 883387
BEHAVIOR CODE 883387
AGE/SEX 891111
COUNTRY 0
COUNTRY CODE 0
STATE 0
STATE CODE 0
COUNTY 893108
COUNTY CODE 893108
IBA CODE 655844
BCR CODE 893108
USFWS CODE 893108
ATLAS BLOCK 893108
LOCALITY 0
LOCALITY ID 0
LOCALITY TYPE 0
LATITUDE 0
LONGITUDE 0
OBSERVATION DATE 0
TIME OBSERVATIONS STARTED 39846
OBSERVER ID 0
OBSERVER ORCID ID 873971
SAMPLING EVENT IDENTIFIER 0
OBSERVATION TYPE 0
PROTOCOL NAME 0
PROTOCOL CODE 0
PROJECT NAMES 849290
PROJECT IDENTIFIERS 849290
DURATION MINUTES 95912
EFFORT DISTANCE KM 278997
EFFORT AREA HA 858798
NUMBER OBSERVERS 16450
ALL SPECIES REPORTED 0
GROUP IDENTIFIER 475518
HAS MEDIA 0
APPROVED 0
REVIEWED 0
REASON 893108
CHECKLIST COMMENTS 791818
SPECIES COMMENTS 844065
Unnamed: 52 893108

In [9]:
for c in df2.columns :
    print(c, len(df2[df2[c].isna()]))

GLOBAL UNIQUE IDENTIFIER 0
LAST EDITED DATE 0
TAXONOMIC ORDER 0
CATEGORY 0
TAXON CONCEPT ID 0
COMMON NAME 0
SCIENTIFIC NAME 0
SUBSPECIES COMMON NAME 860373
SUBSPECIES SCIENTIFIC NAME 860373
EXOTIC CODE 839944
OBSERVATION COUNT 0
BREEDING CODE 883387
BREEDING CATEGORY 883387
BEHAVIOR CODE 883387
AGE/SEX 891111
COUNTRY 0
COUNTRY CODE 0
STATE 0
STATE CODE 0
COUNTY 893108
COUNTY CODE 893108
IBA CODE 655844
BCR CODE 893108
USFWS CODE 893108
ATLAS BLOCK 893108
LOCALITY 0
LOCALITY ID 0
LOCALITY TYPE 0
LATITUDE 0
LONGITUDE 0
OBSERVATION DATE 0
TIME OBSERVATIONS STARTED 39846
OBSERVER ID 0
OBSERVER ORCID ID 873971
SAMPLING EVENT IDENTIFIER 0
OBSERVATION TYPE 0
PROTOCOL NAME 0
PROTOCOL CODE 0
PROJECT NAMES 849290
PROJECT IDENTIFIERS 849290
DURATION MINUTES 95912
EFFORT DISTANCE KM 278997
EFFORT AREA HA 858798
NUMBER OBSERVERS 16450
ALL SPECIES REPORTED 0
GROUP IDENTIFIER 475518
HAS MEDIA 0
APPROVED 0
REVIEWED 0
REASON 893108
CHECKLIST COMMENTS 791818
SPECIES COMMENTS 844065
Unnamed: 52 893108

In [10]:
df1['ALL SPECIES REPORTED']

0       1
1       1
2       1
3       1
4       1
       ..
1815    1
1816    1
1817    1
1818    1
1819    1
Name: ALL SPECIES REPORTED, Length: 1820, dtype: int64

In [11]:
df1.dtypes

GLOBAL UNIQUE IDENTIFIER          str
LAST EDITED DATE                  str
TAXONOMIC ORDER                 int64
CATEGORY                          str
TAXON CONCEPT ID                  str
COMMON NAME                       str
SCIENTIFIC NAME                   str
SUBSPECIES COMMON NAME        float64
SUBSPECIES SCIENTIFIC NAME    float64
EXOTIC CODE                   float64
OBSERVATION COUNT                 str
BREEDING CODE                     str
BREEDING CATEGORY                 str
BEHAVIOR CODE                     str
AGE/SEX                           str
COUNTRY                           str
COUNTRY CODE                      str
STATE                             str
STATE CODE                        str
COUNTY                        float64
COUNTY CODE                   float64
IBA CODE                          str
BCR CODE                      float64
USFWS CODE                    float64
ATLAS BLOCK                   float64
LOCALITY                          str
LOCALITY ID                       str
LOCALITY TYPE                     str
LATITUDE                      float64
LONGITUDE                     float64
OBSERVATION DATE                  str
TIME OBSERVATIONS STARTED         str
OBSERVER ID                       str
OBSERVER ORCID ID                 str
SAMPLING EVENT IDENTIFIER         str
OBSERVATION TYPE                  str
PROTOCOL NAME                     str
PROTOCOL CODE                     str
PROJECT NAMES                 float64
PROJECT IDENTIFIERS           float64
DURATION MINUTES              float64
EFFORT DISTANCE KM            float64
EFFORT AREA HA                float64
NUMBER OBSERVERS              float64
ALL SPECIES REPORTED            int64
GROUP IDENTIFIER                  str
HAS MEDIA                       int64
APPROVED                        int64
REVIEWED                        int64
REASON                        float64
CHECKLIST COMMENTS                str
SPECIES COMMENTS                  str
Unnamed: 52                   float64
dtype: object

In [12]:
df1.tail(5)

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
1815,URN:CornellLabOfOrnithology:EBIRD:OBS1179535736,2024-04-22 09:32:06.882757,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1816,URN:CornellLabOfOrnithology:EBIRD:OBS1182051125,2025-10-02 08:43:08.261022,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1817,URN:CornellLabOfOrnithology:EBIRD:OBS1179535741,2025-10-02 08:42:49.785855,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1818,URN:CornellLabOfOrnithology:EBIRD:OBS1179538852,2025-10-02 08:42:50.128884,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,No visual. Estimated number by calls.,NaN
1819,URN:CornellLabOfOrnithology:EBIRD:OBS1576161579,2025-10-03 13:12:17.533564,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,NaN,NaN,NaN,...,1.0,1,NaN,0,1,0,NaN,NaN,NaN,NaN