## Data Cleaning 01

In this section we will be doing briefly common/basic practices on our first dataframe to prepare our data into more readable insights using pandas.

*Library*

In [1]:
import pandas as pd

**Formatting the columns**

In [2]:
df1 = pd.read_csv('../data/raw/(Loxia_Megapaglaga)ebd_hiscro_relApr-2026.txt', sep='\t', low_memory = False)

df1['NUMBER OBSERVERS'] = pd.to_numeric(df1['NUMBER OBSERVERS'], errors='coerce').astype('Int64')

df1['LAST EDITED DATE'] = pd.to_datetime(df1['LAST EDITED DATE'], errors='coerce')
df1['OBSERVATION DATE'] = pd.to_datetime(df1['OBSERVATION DATE'], errors='coerce')

columns = ['SUBSPECIES COMMON NAME', 'SUBSPECIES SCIENTIFIC NAME']

df1[columns] = df1[columns].fillna('Unknown').astype(str)

In [3]:
df1

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS209001187,2025-10-02 12:09:28.434474,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,3,1,NaN,0,1,0,NaN,Relevamiento rapido de 3 dias,NaN,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS3509436961,2025-10-02 13:55:11.317351,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,<NA>,1,NaN,0,1,0,NaN,WINGS Birding Tours - Leaders: Gavin Bieber an...,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1870620934,2025-10-02 11:36:52.354416,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,4,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS2425022580,2024-08-31 10:45:49.795758,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,5,1,NaN,1,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1654293781,2025-10-04 12:50:19.761621,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,URN:CornellLabOfOrnithology:EBIRD:OBS1179535736,2024-04-22 09:32:06.882757,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1816,URN:CornellLabOfOrnithology:EBIRD:OBS1182051125,2025-10-02 08:43:08.261022,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1817,URN:CornellLabOfOrnithology:EBIRD:OBS1179535741,2025-10-02 08:42:49.785855,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1818,URN:CornellLabOfOrnithology:EBIRD:OBS1179538852,2025-10-02 08:42:50.128884,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,No visual. Estimated number by calls.,NaN
1819,URN:CornellLabOfOrnithology:EBIRD:OBS1576161579,2025-10-03 13:12:17.533564,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN

**Dropping NA values**

We want to drop rows that have missing values in the following columns: 'LATITUDE', 'LONGITUDE', 'OBSERVATION COUNT', 'OBSERVATION DATE', 'NUMBER OBSERVERS', and 'APPROVED'.

In [ ]:
df1_nona2 = df1.dropna( subset=['LATITUDE', 
'LONGITUDE', 
'OBSERVATION COUNT', 
'OBSERVATION DATE', 
'NUMBER OBSERVERS', 
'APPROVED'])

In [ ]:
df1_nona2

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS209001187,2025-10-02 12:09:28.434474,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,3,1,NaN,0,1,0,NaN,Relevamiento rapido de 3 dias,NaN,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS1870620934,2025-10-02 11:36:52.354416,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,4,1,NaN,0,1,0,NaN,NaN,NaN,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS2425022580,2024-08-31 10:45:49.795758,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,5,1,NaN,1,1,0,NaN,NaN,NaN,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS1654293781,2025-10-04 12:50:19.761621,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
5,URN:CornellLabOfOrnithology:EBIRD:OBS1705963839,2025-10-02 11:09:28.428625,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,URN:CornellLabOfOrnithology:EBIRD:OBS1179535736,2024-04-22 09:32:06.882757,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1816,URN:CornellLabOfOrnithology:EBIRD:OBS1182051125,2025-10-02 08:43:08.261022,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1817,URN:CornellLabOfOrnithology:EBIRD:OBS1179535741,2025-10-02 08:42:49.785855,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
1818,URN:CornellLabOfOrnithology:EBIRD:OBS1179538852,2025-10-02 08:42:50.128884,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,No visual. Estimated number by calls.,NaN
1819,URN:CornellLabOfOrnithology:EBIRD:OBS1576161579,2025-10-03 13:12:17.533564,32541,species,avibase-30E7CF04,Hispaniolan Crossbill,Loxia megaplaga,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN

**Eliminating duplicates and unnecessary columns**

In [ ]:
df1_dup3 = df1_nona2.drop_duplicates()

df1_dup4 = df1_dup3.drop(columns=['Unnamed: 52'])

We will be using parquet to keep our formatting.

In [ ]:
df1_dup4.to_parquet('../data/processed/crossbill_clean.parquet', index = False)

df1_clean1 = pd.read_parquet('../data/processed/crossbill_clean.parquet')