## Data Cleaning 02

In this section we will be doing briefly common/basic practices on our second dataframe to prepare our data into more readable insights using pandas.

*Library*

In [1]:
import pandas as pd

**Formatting the columns**

In [2]:
df2 = pd.read_csv('../data/raw/ebd_DO_relApr-2026.txt', sep='\t', low_memory = False)

df2['NUMBER OBSERVERS'] = pd.to_numeric(df2['NUMBER OBSERVERS'], errors='coerce').astype('Int64')

df2['LAST EDITED DATE'] = pd.to_datetime(df2['LAST EDITED DATE'], errors='coerce')
df2['OBSERVATION DATE'] = pd.to_datetime(df2['OBSERVATION DATE'], errors='coerce')

columns = ['SUBSPECIES COMMON NAME', 'SUBSPECIES SCIENTIFIC NAME']

df2[columns] = df2[columns].fillna('Unknown').astype(str)

In [3]:
df2

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS3144018641,2025-05-08 13:55:10.983436,4188,species,avibase-C2077AD8,Antillean Palm Swift,Tachornis phoenicobia,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male collected on this date near Puerto Pl...,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS3144018648,2025-05-08 13:55:11.008615,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,2,0,NaN,0,1,0,NaN,In US National Museum or Field Museum of Natur...,one female collected on this date near Puerto ...,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS3144018640,2025-05-08 13:55:10.978498,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male and one female collected on this date...,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS3144018645,2025-05-08 13:55:10.993761,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Harvard Museum of Comparative Zoology or Fi...,one male collected on this date near Puerto Pl...,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS3144018635,2025-05-08 13:55:10.907722,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,2,0,NaN,0,1,0,NaN,In Field Museum of Natural History and US Nati...,three females collected on this date near Puer...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893103,URN:CornellLabOfOrnithology:EBIRD:OBS4320883276,2026-04-20 08:37:20.831960,6908,species,avibase-1D07B501,White-tailed Tropicbird,Phaethon lepturus,Unknown,Unknown,NaN,...,1,0,G17219962,0,1,0,NaN,NaN,NaN,NaN
893104,URN:CornellLabOfOrnithology:EBIRD:OBS4258562520,2026-04-05 21:23:52.667462,6908,species,avibase-1D07B501,White-tailed Tropicbird,Phaethon lepturus,Unknown,Unknown,NaN,...,9,1,G17089411,1,1,0,NaN,Field Guides Birding Tours,NaN,NaN
893105,URN:CornellLabOfOrnithology:EBIRD:OBS4249387501,2026-04-03 21:30:30.000694,2389,species,avibase-BFBC73AF,White-winged Dove,Zenaida asiatica,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,NaN,NaN,NaN
893106,URN:CornellLabOfOrnithology:EBIRD:OBS4294452790,2026-04-14 09:36:58.996197,7591,species,avibase-C6772490,Yellow-crowned Night Heron,Nyctanassa violacea,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
893107,URN:CornellLabOfOrnithology:EBIRD:OBS4249387507,2026-04-03 21:30:30.000694,35692,species,avibase-A8E1B59A,Yellow-faced Grassquit,Tiaris olivaceus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,NaN,NaN,NaN

**Dropping NA values**

We want to drop rows that have missing values in the following columns: 'LATITUDE', 'LONGITUDE', 'OBSERVATION COUNT', 'OBSERVATION DATE', 'NUMBER OBSERVERS', and 'APPROVED'.

In [4]:
df2_nona2 = df2.dropna( subset=['LATITUDE', 
'LONGITUDE', 
'OBSERVATION COUNT', 
'OBSERVATION DATE', 
'NUMBER OBSERVERS', 
'APPROVED'])

In [5]:
df2_nona2

,GLOBAL UNIQUE IDENTIFIER,LAST EDITED DATE,TAXONOMIC ORDER,CATEGORY,TAXON CONCEPT ID,COMMON NAME,SCIENTIFIC NAME,SUBSPECIES COMMON NAME,SUBSPECIES SCIENTIFIC NAME,EXOTIC CODE,...,NUMBER OBSERVERS,ALL SPECIES REPORTED,GROUP IDENTIFIER,HAS MEDIA,APPROVED,REVIEWED,REASON,CHECKLIST COMMENTS,SPECIES COMMENTS,Unnamed: 52
0,URN:CornellLabOfOrnithology:EBIRD:OBS3144018641,2025-05-08 13:55:10.983436,4188,species,avibase-C2077AD8,Antillean Palm Swift,Tachornis phoenicobia,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male collected on this date near Puerto Pl...,NaN
1,URN:CornellLabOfOrnithology:EBIRD:OBS3144018648,2025-05-08 13:55:11.008615,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,2,0,NaN,0,1,0,NaN,In US National Museum or Field Museum of Natur...,one female collected on this date near Puerto ...,NaN
2,URN:CornellLabOfOrnithology:EBIRD:OBS3144018640,2025-05-08 13:55:10.978498,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Field Museum of Natural History: portal.ver...,one male and one female collected on this date...,NaN
3,URN:CornellLabOfOrnithology:EBIRD:OBS3144018645,2025-05-08 13:55:10.993761,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,In Harvard Museum of Comparative Zoology or Fi...,one male collected on this date near Puerto Pl...,NaN
4,URN:CornellLabOfOrnithology:EBIRD:OBS3144018635,2025-05-08 13:55:10.907722,9840,species,avibase-DC4EA5F1,Broad-billed Tody,Todus subulatus,Unknown,Unknown,NaN,...,2,0,NaN,0,1,0,NaN,In Field Museum of Natural History and US Nati...,three females collected on this date near Puer...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893103,URN:CornellLabOfOrnithology:EBIRD:OBS4320883276,2026-04-20 08:37:20.831960,6908,species,avibase-1D07B501,White-tailed Tropicbird,Phaethon lepturus,Unknown,Unknown,NaN,...,1,0,G17219962,0,1,0,NaN,NaN,NaN,NaN
893104,URN:CornellLabOfOrnithology:EBIRD:OBS4258562520,2026-04-05 21:23:52.667462,6908,species,avibase-1D07B501,White-tailed Tropicbird,Phaethon lepturus,Unknown,Unknown,NaN,...,9,1,G17089411,1,1,0,NaN,Field Guides Birding Tours,NaN,NaN
893105,URN:CornellLabOfOrnithology:EBIRD:OBS4249387501,2026-04-03 21:30:30.000694,2389,species,avibase-BFBC73AF,White-winged Dove,Zenaida asiatica,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,NaN,NaN,NaN
893106,URN:CornellLabOfOrnithology:EBIRD:OBS4294452790,2026-04-14 09:36:58.996197,7591,species,avibase-C6772490,Yellow-crowned Night Heron,Nyctanassa violacea,Unknown,Unknown,NaN,...,1,1,NaN,0,1,0,NaN,NaN,NaN,NaN
893107,URN:CornellLabOfOrnithology:EBIRD:OBS4249387507,2026-04-03 21:30:30.000694,35692,species,avibase-A8E1B59A,Yellow-faced Grassquit,Tiaris olivaceus,Unknown,Unknown,NaN,...,1,0,NaN,0,1,0,NaN,NaN,NaN,NaN

**Eliminating duplicates and unnecessary columns**

In [6]:
df2_dup3 = df2_nona2.drop_duplicates()

df2_dup4 = df2_dup3.drop(columns=['Unnamed: 52'])

We will be using parquet to keep our formatting.

In [7]:
df2_dup4.to_parquet('../data/processed/april-2026-DOchecklist.parquet', index = False)

df2_clean1 = pd.read_parquet('../data/processed/april-2026-DOchecklist.parquet')